---
# tasks file for ansible-nginx-default
- name: Make sure the nginx-locations directory exists
  file:
    path: "{{ nginx_locations_path }}"
    state: directory
    owner: root
  tags:
    - nginx-default

- name: Add default_ssl.conf
  template:
    src: default_ssl.conf.j2
    dest: "{{ nginx_sites_path }}/default_ssl.conf"
  notify:
    - Reload nginx
    - Verify nginxconfig
  when: nginx_default_ssl
  tags:
    - nginx-default
